import Header from '../header';
import Footer from '../Footer';
import Head from 'next/head';

export const Layout = (props) => {
  const { children } = props;
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
