import Head from 'next/head';import Header from './components/Header';
import Footer from './components/Footer';

export default function Design() {
  return (
    <div>
      <Head>
        <title>Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex justify-center">this is design page</div>
      </main>
      <Footer />
    </div>
  );
}
