import Head from 'next/head';import Header from './components/Header';

export default function Website() {
  return (
    <div>
      <Head>
        <title>Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex justify-center">this is website page</div>
      </main>
    </div>
  );
}
